server:
  port: 9003
spring:
  jackson:
    time-zone: Asia/Shanghai
  application:
    name: blind #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://104.233.193.162:3306/blind?characterEncoding=UTF8&useSSL=false
    url: jdbc:mysql://tomysql:3306/blind?characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  #    password: 123456
  redis:
    host: 104.233.193.162
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:6868/eureka/
      defaultZone: http://104.233.193.162:6868/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
jwt:
  config:
    key: itcast
    ttl: 360000

